# Generated by Django 4.2.5 on 2023-09-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('loc_x', models.FloatField(max_length=16)),
                ('loc_y', models.FloatField(max_length=16)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
