# Generated by Django 4.2.5 on 2023-09-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationinfo',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='locationinfo',
            name='loc_x',
            field=models.FloatField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='locationinfo',
            name='loc_y',
            field=models.FloatField(blank=True, max_length=16, null=True),
        ),
    ]
